### ISSUE TITLE
HorizonsEphemeris Comments

### ISSUE THREAD

**Issue by andrew-saydjari** [JuliaAstro/EphemerisSources.jl#14]
- [x] The example uses earth.X and earth.Y, but you have to use earth.x and earth.y.
- [x] The compat for HorizonsEphemeris requires HorizonsAPI = "0.1" which is limits it to any version <v1.0.0, but HorizonsAPI is not v1. It would be good to update this compat, and possibly add automated CompatHelper checking to help track things like this.
- [x] I briefly tried to pass ephemeris an AstroTime epoch. I failed. If it is possible, documenting it would be helpful. If not, this might be a feature request (which you should not view as acceptance blocking), but that would be really nice.
- [x] I *think* that all of the names you can pass are listed here (https://naif.jpl.nasa.gov/pub/naif/). If so, it would be good to be explicit about the list of "bodies" that ephemeris can take and document that clearly (ideally both in overview and in the local page).
- [x] Default units of ephemeris appear to be AU-D, rather than KM-S which is what I would have expected based on https://ssd-api.jpl.nasa.gov/doc/horizons.html. If you have made a choice to have a default that is inconsistent with the default specified there, I think it is necessary to document that.

**Comment by jdc-pub** [comment]
I've fixed `AstroTime` support, changed the default units to `KM-S` to match Horizons (good catch!), and addressed the other comments in [`1d0925cef8`](https://github.com/JuliaAstro/EphemerisSources.jl/commit/1d0925cef86d4bb8dd064f9e1bcf8bae789391ef).

**Comment by andrew-saydjari** [comment]
It appears the example plot

plot(
   earth.x, earth.y;
   aspect_ratio = 1,
   linewidth = 1.5,
   border = :none,
   size = (600, 600),
   dpi = 200,
   grid = false,
   axis = nothing,
   title = "",
   label=:none,
   color = "green",
   background=:transparent,
)

Has been removed from HorizonsEphemeris.jl? Any reason why? I thought it was great!

**Comment by andrew-saydjari** [comment]
I cannot reproduce the AstroTime support, but maybe I am doing something wrong with the versioning. I am using [05ee1981] HorizonsEphemeris v1.2.1. I would have installed from git like I did with Pkg.add(url="https://github.com/JuliaAstro/EphemerisSources.jl") to get the latest version, but the subpackages (like HorizonsEphemeris) do not seem to have git pages that allow direct download.  Can you either update the registered package or tell me if my invocation is wrong?

```
ep = TTEpoch(59235.0days, origin=:modified_julian)

earth = let start = ep - 50years, stop = ep + 50years, step = 1days
   @time ephemeris("earth", start, stop, step; wrt="jupiter", units="AU-D");
    # what are my units choices, what are my named bodies options?
end
```

Everything else listed on this issue has been resolved.

**Comment by jdc-pub** [comment]
Do you mean [this plot](https://juliaastro.org/EphemerisSources.jl/docs/dev/examples/horizons/#Reference) above the _References_ section? It's pretty hidden by that massive DataFrame. I've reduced the number of rows in the latest version of the docs.

Good catch, it seems `HorizonsEphmeris` had an issue where it allowed floating point types for the `interval`, but Horizons does not. I've corrected this. In the latest version of the project, I was able to run the code example you provided above. 

As for the units and bodies choice, I don't know if Horizons supplies a full list of the bodies it supports. For the units, I updated the doctoring for `ephemeris` to clarify that units of KM-S, KM-D, and AU-D are supported.

**Comment by andrew-saydjari** [comment]
Yes. I did not scroll down past that huge table. You might just invert the order or trim the data frame to only a few lines (I still see 261 lines...). But ok, thanks for pointing out my error there. Style choice to you if you want to increase its visibility.

Sorry for the comment in my AstroTime example. I think you already had answered that question previously. That was just a leftover note to myself when I was doing the first review pass.

I am still not able to run the code example however.  [858900df] EphemerisSources v0.3.0 [https://github.com/JuliaAstro/EphemerisSources.jl.git#main](https://github.com/JuliaAstro/EphemerisSources.jl.git#main%60). This still gives me the error.

```
The data delimiters ($$SOE, $$EOE) were not found in the response! 

	Unknown units specification -- re-enter
```

Part of me might be confused with how users *should* be invoking these subpackages. Should people really being calling Pkg.add("HorizonsEphemeris"), or should they do Pkg.add("EphemerisSources") and calling the subpackages as EphemerisSources.HorizonsEphemeris.ephemeris, for example? I tried the latter when trying this time, to ensure I had the most recent version of the code.

**Comment by jdc-pub** [comment]
> Part of me might be confused with how users should be invoking these subpackages. Should people really being calling Pkg.add("HorizonsEphemeris"), or should they do Pkg.add("EphemerisSources") and calling the subpackages as EphemerisSources.HorizonsEphemeris.ephemeris, for example? I tried the latter when trying this time, to ensure I had the most recent version of the code.

Users should be able to do either, but I had intended users to use individual sub-packages if they knew what they needed, and use `EphemerisSources.jl` if they want everything at once. 

> I am still not able to run the code example however. 

Sorry about that. I do think this is fixed now. I also added this as a [test](https://github.com/juliaastro/ephemerissources.jl/blob/main/lib/HorizonsEphemeris/test/runtests.jl) to `HorizonsEphemeris`, and it is passing. Could you please try one more time? Maybe the recent `HorizonsEphemeris-v1.3.0` version update fixed things.

**Comment by andrew-saydjari** [comment]
Interesting. It does appear fixed in HorizonEphemeris-v1.3.0 just using the ephemeris exported there. However, before doing that update, git installing EphemerisSources and using EphemerisSources.HorizonsEphemeris.ephemeris was still failing, but after doing the Pkg.update("HorizonEphemeris") EphemerisSources.HorizonsEphemeris.ephemeris started working. This suggests to me that there is some sort of dependency issue. Maybe it means that the Project.toml for EphemerisSources was being satisfied by the HorizonEphemeris v1.2.0 I had installed and so it was not updating it... but I would have thought a direct git install would have gotten the most recent/up to date HorizonEphemeris version directly through the subfoldering. Just calling this out because it did not work as I expected.

In any case, yes, I agree the functionality for AstroTime has been included. Just a note about verifying subpackage versioning.
